version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ai-cv-backend
    network_mode: host
    volumes:
      - ./backend/static:/app/static
      - ./backend/cv_faiss_index:/app/cv_faiss_index
      - ./backend/photos:/app/photos
    env_file:
      - ./backend/.env
    restart: unless-stopped
    # ports: 8000:8000  <-- УБРАТЬ, host mode не поддерживает ports

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai-cv-frontend
    network_mode: host
    depends_on:
      - backend
    restart: unless-stopped
    # ports: 3000:3000 <-- тоже убрать
